[package]
name = "init_config"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
log = "0.4.22"
regex = "1.10.6"
winres = "0.1.12"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
